services:
  app:
    build:
      context: .
      dockerfile: app-Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - /medods_testcase/app.env
    restart: on-failure

  db:
    build:
      context: .
      dockerfile: db-Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=testcase_api
      - POSTGRES_PASSWORD=testcase_api_password
      - POSTGRES_DB=auth_testcase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testcase_api -d auth_testcase"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: